### ISSUE TITLE
Error during niftypet install

### ISSUE THREAD

**Issue by BanorHlaalu** [NiftyPET/NiftyPET#7]
Hi,

When I'm trying to install niftypet using the anaconda promp, I'm getting the following errors (I tried multiple different windows 10 machines). Can anyone help me with that? I'm happy to provide more information if necessary.
[Errors.txt](https://github.com/NiftyPET/NiftyPET/files/6938795/Errors.txt)

**Comment by casperdcl** [comment]
ah you're doing a non-GUI installation on windows.

Should be fixed soon (https://github.com/NiftyPET/NInst/pull/18) but for now you could set both `PATHTOOLS` and `HMUDIR` to your desired directories, for example:

```bash
set PATHTOOLS=$AppData%\NiftyPET_tools
set HMUDIR=$AppData%\mmr_hardwareumaps
pip install niftypet
```
